sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iYXpKh6Y0f2Vus5fhAqnOZ4ozVWBOg7lLZPRVhTrpoOwjPqGyF42Kpr/4h/AXQOZ1mYGrMSrTDz2lB5RKNzQDc414NekisqhTPY3VH+NwGs1OPZC9kwwebYvXm4kWFKIm/YLZZ6W2txzXHhmhM4anbCOdVhzJFACrCFHtMqkl+lAN+CpbNEKzBXZ4v484rP2mGLh1w/hOl2gKL4sYJ+XGH5yb1TJKzE66O+e/t7CMirUjJP4x66R0pRKbywTxP1YBKM7agG/oPhN+pwODEvCSKVFpOaHgjU1VCgUO+2ugh6Sl/32rI3nI7e0Z3eF3KuBS1yHyK4yzGzaZsgV6Y64Z5d9wJQIrNx6Xjcc5gUCULL+z2z9R+t8/EJn/V9o1ZPlmU+YinF1QBFwAgYC4J6sppbM3mDIeyEtUxCaagN1PaxG/KIQFOuGShluoLHLROPKg20gp758XR/Vzb39mYm5LIRJX5kUxfvgAMJYqqRu6reLaS6BmNXQK5znRkiKaW0pElkWDhXY7RkIiT1FYbmj+8FW5oRBDzbgFIpep+glWmAST36oF3nwNfdhhQw0dLlfgW9k3vkiZch9EXQXLKlkDMuv5Plk7e+T66sQK3JVXZKZmukUSsWugXg+mLEEwX2qvmTOqXuPQJ84vmGoSLOOab/1l0CLGnY4a9+BaJyJjW4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Universal-Copyright-Convention--1988-_253
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy